server:
  port: 8103
spring:
  cloud:
    gateway:
      default-filters:
        - AddResponseHeader=source, ghost
      routes:
        - id: api_route
          uri: http://localhost:8102
          predicates:
            - Path=/api/**
logging:
  level:
    org:
      springframework:
        cloud:
          gateway: trace
dubbo:
  application:
    name: dubbo-springboot-demo-provider
  protocol:
    name: dubbo
    port: 20880
  registry:
    id: nacos-registry
    address: nacos://localhost:8848
